### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.gimp.GIMP#1]
Is it possible to build the [help content](https://download.gimp.org/mirror/pub/gimp/help/)? Possibly only as an optional extension as it's very large but it'd be really helpful for some of Endless' totally offline users.

**Comment by Jehan** [comment]
Hi!

It has actually been planned for months and I first wanted to build these as extensions. But flatpak developers on irc (i.e. @alexlarsson in particular) told me it would actually be better to make a special extension case for these. So now I am waiting for upstream to add this feature. Cf. https://github.com/flatpak/flatpak/issues/1086

Now this is out of my hands and your best bet is to bother flatpak people to have them implement the feature. :P
When this will happens, I will continue this project of providing the GIMP manual through flatpak.

**Comment by nedrichards** [comment]
That's great, thanks.

**Comment by Jehan** [comment]
Just for the record, I can't handle all bugs related to flatpak integration by myself. I am already overwhelmed and need to recenter my activities to the features we actually need for our activity (which is animation film!). So if anyone wants to see this implemented, I would gladly merge a patch adding manuals as an extension. But I won't do such patch myself in the foreseeable future.

For anyone who wants to implement, here is the comment by @alexlarsson on flatpak/flatpak#1086, which should help as a good hint to get started:

> The locale-subset property of extensions should allow this now.

**Comment by hfiguiere** [comment]
I have something working (locally).

Can't get it to build in a separate package though (thanks to Python 2.7), so the GIMP build takes even longer.

**Comment by nedrichards** [comment]
Resolved by https://github.com/flathub/flathub/pull/1599
