### ISSUE TITLE
Not visible in GNOME Software

### ISSUE THREAD

**Issue by jurf** [flathub/org.gimp.GIMP#12]
Original report: https://twitter.com/alexb3d/status/992538697252864000

I can confirm, running F28, GS 3.28.

**Comment by TingPing** [comment]
`pkill gnome-software && gnome-software --verbose`

**Comment by jurf** [comment]
[gs-no-gimp.log](https://github.com/flathub/org.gimp.GIMP/files/1984459/gs-no-gimp.log)

**Comment by TingPing** [comment]
Logs show it finding it just fine.

**Comment by jurf** [comment]
Definitely doesn’t show though, even with `env LANG=C`.

**Comment by TingPing** [comment]
Seems like a duplicate of #8

**Comment by Lvaskz** [comment]
Yes same problem, gimp not shows in gnome software ubuntu 18.04
