### ISSUE TITLE
Error about slang

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.gimp.GIMP#129]
When launching GIMP on the command line, since runtime 41, I get this error:

```
/app/lib/gimp/2.0/plug-ins/file-aa/file-aa: error while loading shared libraries: libslang.so.2: cannot open shared object file: No such file or directory
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
```

Not sure what `file-aa` is but the indication is that the plugin won't work.

I filed an issue with GNOME:
https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/463

**Comment by hfiguiere** [comment]
The solution is to build slang, or if it's optional to disable it.

The problem is that slang is in the SDK, therefor it is detected at build time.

**Comment by Jehan** [comment]
> Not sure what file-aa is but the indication is that the plugin won't work.

For information, `file-aa` is the plug-in for ASCII art export.

> The solution is to build slang, or if it's optional to disable it.

It's probably not useful. Seems like aalib has `--with-slang-driver=no` option. I would suggest to try this option, then run GIMP, create an image and export it as ASCII Art (I think name it as "something.txt") and see if it works. 🙂
