### ISSUE TITLE
No dark theme for the beta version

### ISSUE THREAD

**Issue by vincentbernat** [flathub/org.gimp.GIMP#133]
Hey!

The beta version does not ship a dark theme, unlike the stable version. Could this be added?

Thanks.

**Comment by Jehan** [comment]
Dark themes don't work the same way anymore in GIMP 3.0. If you look at the bottom of the theme selection page in Preferences, you'll notice a checkbox "Use dark theme variant if available". Check this box and if your currently selected theme has a dark variant, it will be used.

Unfortunately we don't have custom themes for GIMP 3.0 right now. We do plan to make at least 2 (one with Dark/Light variants, and a neutral gray one), but we are waiting for theme contributors.

In any case, this is not a report about the package, but GIMP itself, so it's not the right place to report (this is a full vanilla package, we don't add anything extraneous). Therefore I propose to close this report.

But don't worry, this is planned eventually.

**Comment by vincentbernat** [comment]
Thanks! I thought the dark theme may be missing from the Flatpak. Let's close the issue then.
