### ISSUE TITLE
Please update the runtime for the beta channel

### ISSUE THREAD

**Issue by sukahiroaki** [flathub/org.gimp.GIMP#140]
Title says it all: The beta channel is still on the GNOME 40 runtime (while stable is on 41) which is getting awfully close to being EOL'd.

**Comment by hfiguiere** [comment]
give it a few hours

**Comment by sukahiroaki** [comment]
Build seems to have failed, though. (both actually)

https://flathub.org/builds/#/builders/32/builds/83510

**Comment by sukahiroaki** [comment]
Ah, I see gitlab.g.org was down. So I guess someone pushing a new build should be sufficient. Sorry for the noise.

**Comment by hfiguiere** [comment]
as I mentionned in the PR there was an infra issue. it's going now.
