### ISSUE TITLE
Wayland with mixed DPI monitor setup not working correctly for GIMP

### ISSUE THREAD

**Issue by hzulla** [flathub/org.gimp.GIMP#150]
Please see https://github.com/flatpak/flatpak/issues/5033 for details.

If you run the flatpak version of GIMP on Ubuntu/Wayland and have two monitors attached with different scaling, the GIMP UI will not change its scaling when moved from the hidpi monitor to the lodpi monitor and back.

The workaround --nosocket=fallback-x11 --nosocket=x11 --socket=wayland mentioned on https://github.com/flatpak/flatpak/issues/5033 works for Wayland-aware applications like Firefox, but not for flatpak GIMP.

I do not know if this is a generic flatpak issue or if it is a packaging problem.

**Comment by Jehan** [comment]
> The workaround --nosocket=fallback-x11 --nosocket=x11 --socket=wayland mentioned on https://github.com/flatpak/flatpak/issues/5033 works for Wayland-aware applications like Firefox, but not for flatpak GIMP.

Which flatpak is it? The stable one or the development one? If the stable one (2.10 series), then it is GTK+2, hence not Wayland aware.

The development flatpak (2.99 series, future GIMP 3.0) should be Wayland aware. If you were using stable GIMP, could you try the same thing with the development flatpak: https://www.gimp.org/downloads/devel/

Then tell us how it goes.

**Comment by hzulla** [comment]
Thanks for your response.

Yes, I used the stable version from flathub.

Tried version 2.99.10 as requested. That version works as expected! Bug is fixed there.

**Comment by Jehan** [comment]
So no flags/permissions to add to the development flatpak?

As for the stable one, if the feature depends on the software itself being Wayland aware, there is probably not much to be done. GIMP 2.10.x are not Wayland aware and they probably won't ever be.

**Comment by hzulla** [comment]
> So no flags/permissions to add to the development flatpak?

No, nothing to add. The development version worked as expected, so this issue will be fixed once it turns to the stable version.
