### ISSUE TITLE
Can't pin GIMP to Task Manager

### ISSUE THREAD

**Issue by rolodoom** [flathub/org.gimp.GIMP#162]
I'm testing flatpak from flathub and I noticed that it's not possible to pint the GIMP icon to the Task Manager as I can with other applications. The option is just not available as seen on the screenshot. Is anyone else having this same behavior?

![Screenshot_20221109_084818](https://user-images.githubusercontent.com/61945227/200847233-a60f3aa3-6e92-4ed8-a9f4-d33a8fab3bd8.png)

**System:**
* **OS:** Manjaro KDE
* **Desktop:** Plasma 5.25.2
* **Kernel:** 5.15.76-1-MANJARO

**Comment by Jehan** [comment]
@rolodoom Do you still have this issue? I personally have no idea what could be the problem. On GNOME at least, I can pin GIMP's flatpak no problem. 🤷

Are the other applications you try with also flatpaks? Could you try if you can pin other flatpaks?

**Comment by rolodoom** [comment]
Yeah, I still have the problem on KDE.  I use other flatpaks and only getting problems with GIMP as far as I know. Would be nice to know where to look to find the solution.

**Comment by rolodoom** [comment]
I just tested, there is no problem with the development Flatpak of GIMP. 

Tested on Archlinux - KDE.

**Comment by HarryMichal** [comment]
So, my 2c would be that this is related to GTK2 behaviour combined with KDE Plasma. Another test worth doing is to try to reproduce this issue with GIMP installed via Pacman instead of the flatpak app. If you'd be able to reproduce it then it's not a problem of the flatpak but of GIMP itself (the current stable version).

**Comment by xalt7x** [comment]
Upsteam issue: https://gitlab.gnome.org/GNOME/gimp/-/issues/11009

**Comment by brunvonlope** [comment]
GIMP 2.10.38 released in 2024-05-05. Closing as fixed.
