### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by razzeee** [flathub/org.gimp.GIMP#201]
It would be nice to have screenshots

**Comment by razzeee** [comment]
When I opened this flathub did not have any screenshots. Both not via the website or via gnome software.

Looking at the Definition, it seems weird to have more then one default screenshot, but I'm not sure that would cause it to drop all screenshots?

**Comment by razzeee** [comment]
https://flathub.org/api/v2/appstream/org.gimp.GIMP doesn't have a screenshot for e.g.

**Comment by Jehan** [comment]
Maybe I misunderstand the issue or there was a temporary issue on Flathub when you reported this issue. There are indeed definitely screenshots of GIMP right now on Flathub (I see them right now in Flathub and in GNOME Software) and it's not new at all (we had them for years).

As for the multiple default screenshots, it is not a bug. A software can have multiple important area of usage which we want to show prominently (e.g. for us, digital painting and photography). The [AppStream spec clearly says](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots):

> The <screenshots/> tag contains multiple <screenshot/> children, where at least one of them must have the property type="default" to indicate the primary screenshot of the software.

Note the *at least* wording and not *exactly* for instance. So yeah, there are to be at least 1, and possibly more, default screenshots. It's not a bug.

Anyway not sure if I am missing something or misunderstood what this report is about. Right now, it seems like there might just have been a mistake, or else there was a temporary issue when this was reported so you couldn't see the screenshots. Anyway they are there. 😄

**Comment by razzeee** [comment]
Yeah, it's working again, no idea why. Feels like maybe appstream-glib had a problem and broke on parsing that part.

Anyway, I'll close this, not much we can figure out without having the problem. Sorry for the noise.

**Comment by Jehan** [comment]
No prob. Thanks for reporting possible problems in the package! :+1:
