### ISSUE TITLE
Verify ownership on beta.flathub.org

### ISSUE THREAD

**Issue by barthalion** [flathub/org.gimp.GIMP#204]
We're preparing for the launch of beta.flathub.org, and would like to see your app verified as maintained by its developers. Currently, I've marked it as such manually, but it would be preferred to use one of the verification features. This can be initiated by logging it at https://beta.flathub.org/login with a GitHub account, pressing "Developer Settings" and following the instructions there.

**Comment by Jehan** [comment]
P.S.: by the way, I see that we can log-in with GNOME Gitlab on the new Flathub. Does it mean we'd be able to move this repository to GNOME Gitlab too? I would really like if we could. We like to have all our repositories there.

**Comment by Jehan** [comment]
Ok.

P.S.: I edited the testing link in my above comment as I wrote the wrong one:  https://testing.gimp.org/.well-known/org.flathub.VerifiedApps.txt

It's now up. Just not on the main website yet.

**Comment by Jehan** [comment]
Ok. It's now verified (the developer settings say so), except I don't see the small check mark on GIMP's page on the new Flathub.

@barthalion Do we just have to wait a bit then it will appear later? Maybe these are added as batch at regular interval?

**Comment by Jehan** [comment]
Indeed now it's there. Thanks @Tibladar !
Closing.
