### ISSUE TITLE
Whenever I run GIMP, systemd logs: Failed to add PIDs to scope's control group: Permission denied

### ISSUE THREAD

**Issue by marcelpaulo** [flathub/org.gimp.GIMP#23]
I've installed GIMP **2.10.2** on Xubuntu **18.04** from flathub, using flatpak **0.11.7-flatpak1~bionic** (from PPA ***alexlarsson/flatpak***)

```
paulo:~$ flatpak info org.gimp.GIMP 
Ref: app/org.gimp.GIMP/x86_64/stable
ID: org.gimp.GIMP
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2018-05-27 05:24:02 +0000
Subject: Update GNOME's git repository URIs. (b6030b22)
Commit: 713afa59afac8c8b272ff0c8967e4d53c1ed9e2ae3a8cbb730aa850dc6f3e596
Parent: 2407166fa08405dba99b6ba45ff946d83fee7ff00c0c09ec1dd23736dbc71108
Location: /var/lib/flatpak/app/org.gimp.GIMP/x86_64/stable/713afa59afac8c8b272ff0c8967e4d53c1ed9e2ae3a8cbb730aa850dc6f3e596
Installed size: 203,1 MB
Runtime: org.gnome.Platform/x86_64/3.28
```

GIMP has been working without any problems, but I've noticed that, whenever I start it, these messages are logged in the systemd journal:

```
jun 05 19:56:06 monk systemd[1352]: flatpak-org.gimp.GIMP-2553.scope: Failed to add PIDs to scope's control group: Permission denied
jun 05 19:56:06 monk systemd[1352]: flatpak-org.gimp.GIMP-2553.scope: Failed with result 'resources'.
jun 05 19:56:06 monk systemd[1352]: Failed to start flatpak-org.gimp.GIMP-2553.scope.
```

I don't know systemd deeply enough to know what are the consequences of this failure.

**Comment by Jehan** [comment]
Does it happen only with GIMP's flatpak? Or other flatpak?
I have no idea what these messages mean either. For the record, when I start GIMP's flatpak, I only get this systemd log:

> juin 06 01:53:49 DarkMarmot systemd[5951]: Started flatpak-org.gimp.GIMP-20403.scope.

**Comment by marcelpaulo** [comment]
It's the only flatpak I have installed. But I'll install another one, to compare.

I worked with GIMP today and had no problems, in spite of those messages.

**Comment by marcelpaulo** [comment]
Bingo ! Found out this flatpak issue, flatpak/flatpak#1216, complaining of exactly the same problem, which happens to various flatpaks. It's caused by a systemd issue, systemd/systemd#3388, which has already been fixed by systemd/systemd#8125, which is in system release **v238**.

I have just checked, Xubuntu 18.04 runs systemd **v237**. I fear replacing Ubuntu-packaged systemd, since all userland applications are managed by it, and breaking it would be catastrophic. flatpak/flatpak#1216 recommends as a workaround to boot with:

```
systemd.legacy_systemd_cgroup_controller=1
```

So I'll try that, and if it works I'll post here for reference. But I'll close this issue now since it has nothing to do with the way you guys packaged the GIMP flatpak.

**Comment by marcelpaulo** [comment]
For the record, the workaroud works ! I rebooted, pressed *Shift* to open up GRUB, added `systemd.legacy_systemd_cgroup_controller=1` to the `linux` boot line, started GIMP, and now the message in the systemd journal is just:

```
jun 05 22:16:40 monk systemd[1451]: Started flatpak-org.gimp.GIMP-1946.scope.
```

**Comment by marcelpaulo** [comment]
If anyone else gets bothered with those error messages, the cause and workaround are now documented here.

**Comment by marcelpaulo** [comment]
Just complementing, to round off the workaround, for Ubuntu-based environments:

1. Edit ***/etc/default/grub***, change:

    ```
    GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
    ```
    to:
    ```
    GRUB_CMDLINE_LINUX_DEFAULT="quiet splash systemd.legacy_systemd_cgroup_controller=1"
    ```
2. Run:
    `sudo update-grub`
3. Reboot
