### ISSUE TITLE
Update beta to GNOME 45

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.gimp.GIMP#251]
Update beta to GNOME 45

This is currently blocked by this:

https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/736

tl;dr GIMP link against libappstream-glib but it is removed in the platform while still in the SDK.

**Comment by Jehan** [comment]
Yeah we had the issue months earlier on the nightly flatpak of GIMP (which uses the `master` version of the GNOME runtime) so I added libappstream-glib build in there already last April. The same build rules should work, I guess, on the beta (especially as it's very close to the nightly build): https://gitlab.gnome.org/GNOME/gimp/-/blob/master/build/flatpak/org.gimp.GIMP-nightly.json?ref_type=heads#L49

**Comment by hfiguiere** [comment]
yeah this is the approach to take. but it remains a bug in the SDK. If they didn't want people to link it, they shouldn't provide the .pc.

**Comment by hfiguiere** [comment]
I'll submit a PR later today.

**Comment by Jehan** [comment]
> yeah this is the approach to take. but it remains a bug in the SDK. If they didn't want people to link it, they shouldn't provide the .pc.

Sure, definitely!

> I'll submit a PR later today.

👍
