### ISSUE TITLE
Document duplicated dependencies

### ISSUE THREAD

**Issue by hadess** [flathub/org.gimp.GIMP#27]
It's already in the Freedesktop SDK 1.6 as well as the current master, as well as in the GNOME SDKs based on that, so it shouldn't be necessary to have it built again:
https://github.com/flathub/org.gimp.GIMP/blob/master/org.gimp.GIMP.base-modules.json#L248

**Comment by Jehan** [comment]
I always check my dependencies.
GIMP 2.10 needs libwebp 0.6.0 or over. The yocto-build base image contains libwebp 0.5.1.

This is not the only case. We also build libpng and lcms2 for instance for the same reason (the GNOME SDK has them but they are too old).

Also we use the last GNOME SDK. So I will close, because there is nothing to do here.
Feel free to reopen if I actually missed something; but as far as I can see (and I double-checked again just now), we need to build libwebp.

**Comment by hadess** [comment]
Let me reword that then.

**Comment by hadess** [comment]
You can use C-style comments in the json-glib version of GLib, which would allow to mention that you're building this particular version of the library because a newer version is required, for example:
`/* GIMP 2.10 needs libwebp 0.6.0 or over */`
above the module definition would be great, to avoid this sort of problems in the future.

**Comment by hadess** [comment]
I can't reopen the issue, so if you could, that'd be great.

**Comment by hadess** [comment]
(Also, 1.0 is the latest upstream version of libwebp, might be worth updating to that)

**Comment by hadess** [comment]
The two-liner for the last comment.
```
-                    "url": "http://downloads.webmproject.org/releases/webp/libwebp-0.6.0.tar.gz",
-                    "sha256": "c928119229d4f8f35e20113ffb61f281eda267634a8dc2285af4b0ee27cf2b40"
+                    "url": "https://github.com/webmproject/libwebp/archive/v1.0.0.tar.gz",
+                    "sha256": "84259c4388f18637af3c5a6361536d754a5394492f91be1abc2e981d4983225b"
```

**Comment by Jehan** [comment]
Fixed with:

```
commit b2647be01243608f55520ea91d1936683bd8975a
Author: Jehan <jehan@girinstud.io>
Date:   Mon Sep 24 15:32:35 2018 +0200

    Issue #27:  Document duplicated dependencies.
    
    I already had a "duplicate-dependencies" module, which was quite
    self-documented by its name. libwebp should have been under this module
    though.
    Also add a comment to make double-sure the purpose of these duplicate
    dependencies is obvious.

 org.gimp.GIMP.base-modules.json | 29 +++++++++++++++++------------
 1 file changed, 17 insertions(+), 12 deletions(-)
```

**Comment by Jehan** [comment]
I also just updated to libwebp 1.0.0. I didn't use the github link, which is not the main source code. This is only a mirror and if experience told us anything, this is to avoid rely on such platforms as upstream sources when possible (here there are much better upstream servers, reliable ones, this is where we should download the source).

**Comment by hadess** [comment]
Much clearer, thanks!
