### ISSUE TITLE
Do not show grids on KDE Neon 5.14

### ISSUE THREAD

**Issue by rexrod** [flathub/org.gimp.GIMP#36]
By ticking 'show grid', the grid does not appear as it should. And the 'configure grid' option has no effect at all.

```sh
cat /etc/lsb-release
DISTRIB_ID=neon
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="KDE neon User Edition 5.14"

flatpak --version
Flatpak 1.0.2
```

**Comment by Jehan** [comment]
Hello,

Are you sure you set the grid correctly, in particular with relevant spacing (neither too small, in which case, GIMP may not show it depending on the zoom; nor too big, in particular bigger than the canvas)?

I just tested on flatpak GIMP, and grids worked fine here.

**Comment by rexrod** [comment]
I believe so. I made the test with the same options, height and width of 32x32px, grid with 1px each, to work with pixel art, in gimp 2.10 through the native installation via ppa and worked normally.

**Comment by Jehan** [comment]
Well I am unsure what to say as I cannot reproduce. I would suggest to try again and:

1. make sure that you did check "View" > "Show Grid"
2. make sure that you are using appropriate grid configuration, spacing in particular.

Other than this, I have no idea. My guess would be that there was a slight misconfiguration when you tried and didn't notice it. Of course, I may be wrong and maybe you indeed encountered a bug. If so, it would be great if you could try and understand what are the triggers and how I could reproduce it.

Also I don't think there is anything specific to the flatpak build for this issue (though here too, I could be wrong, yet I really don't see where the build could create an issue with the grid feature).

**Comment by rexrod** [comment]
I am using the native version now, but as soon as I can reproduce the possible bug, I report all the necessary details and prints. For the time being, feel free to close the activity. Thank you.
