### ISSUE TITLE
GIMP windows changed from full to small just after open a file !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.gimp.GIMP#47]
Hi. I tried GIMP from flatpak on Fedora 28 X64 Cinnamon but it has problem: at 1st when launch it it open along area of screen. But just after open an image then it's window size will become small ! Moreover it should be an icon on upper right corner of it's window to be used to maximize/demaximize window but it has no such icon ! In fact at upper right corner there are just: - x icons

**Comment by Jehan** [comment]
> Moreover it should be an icon on upper right corner of it's window to be used to maximize/demaximize window but it has no such icon ! 

GIMP does not control the buttons on the Windows decoration. This is up to your desktop (i.e. Cinnamon in your case). If some window management icons ((de)maximize) is missing, then it is a problem with Cinnamon.

As for the other issues, I am sorry, but I don't really understand the report. Could you try to explain it again? Maybe upload screenshots if it is difficult to explain. Thanks.

**Comment by Nokia808** [comment]
@Jehan 
Hi. Sorry for delay. I took 2 screenshots: 1st is program after launch it & before perform any operation. 2nd screenshot show it's view just by perform any operation (like opening a file). I can not restore view of program to size of that of screenshot number 1.

Please look for upper right corners of both screenshots & icons at this area. You see only 2 icons: - x while they should be 3 (additional one between - & x). No any program or GUI suffer from such issue !!

![1](https://user-images.githubusercontent.com/25375330/52903924-a0d07580-321c-11e9-9433-96f7ece5079f.png)

![2](https://user-images.githubusercontent.com/25375330/52903928-a928b080-321c-11e9-9fd4-533424991b25.png)

**Comment by Jehan** [comment]
Ok I understand the problem. The windows is too big for your screen. This happens sometimes with screen of not too big resolution, as some docks minimum size can be a bit high. You may try to grow the dock horizontally first (to have more than 3 columns of tool icons) and see how it goes.

If it is still not enough, try to play with the horizontal separator between the top right and bottom right docks. Indeed I can see that the separator is quite low, and I don't think any of the top right dockables need that much height. So they are just eating on bottom space for no reason.

Finally if nothing is working so far, detach dockables one by one (click the small arrow at top right of the dock and select "Detach tab") to see which one is just requesting too much space.

As for the reason why you don't have the Maximize icon, it is also for the same reason. As I said, the window is already taller than your screen at minimum size. So it cannot be maximized (which in this case would mean make it smaller than its minimum size). This is why most window managers would just remove the Maximize button.

Anyway this is a general problem of GIMP (not flatpak specific) that some of the dockables need a bit too much vertical space. We have been trying to improve this, but it is still true. GIMP is really better adapted to big resolution screens. With smaller screens, you need to detach the higher dockables.

Thus I will now close this report. If you can find that a given dockable is really too tall and have suggestions to improve the vertical usage, then you may open a bug report for this (on upstream GIMP bug tracker). Other than this, I don't have anything better to propose.

**Comment by Nokia808** [comment]
O.K I tried some of your suggestions & ended by failure ! It seem that this represent a great regression in GIMP because my GIMP version 2.8.22 has no such problem as all ! I'm about 3 years user of Fedora Linux & since 1st day of using Fedora 24 till now (Fedora 28) using GIMP from Official repositories without suffering from such problem !

I will open a bug in GIMP bugzilla tomorrow !
