### ISSUE TITLE
GIMP on KDE Neon doesn't use Breeze theme correctly

### ISSUE THREAD

**Issue by lephuongbg** [flathub/org.gimp.GIMP#80]
Not sure if it is because of KDE Neon, but GIMP doesn't use Breeze theme, results in ugly fallback GTK theme:

![image](https://user-images.githubusercontent.com/1001176/90113938-fe4f6f00-dd8c-11ea-8de9-bbb10f43311e.png)

The Breeze theme is already installed:

```
❯ flatpak install flathub org.gtk.Gtk3theme.Breeze
Looking for matches…
Skipping: org.gtk.Gtk3theme.Breeze/x86_64/3.22 is already installed
```

**Comment by Jehan** [comment]
GIMP 2.10.x is based on GTK+2. It cannot use GTK+3 themes yet (I can see the breeze theme you are using is a GTK+3 one).

Now why does your GIMP look like this, I am unsure. Have you manually changed the theme in `Edit > Preferences > Interface > Theme`? Which one is currently set?

**Comment by lephuongbg** [comment]
I see. It is currently using system theme:

![image](https://user-images.githubusercontent.com/1001176/90198595-136be280-de0d-11ea-809d-1341a6bc9611.png)

Switching it to light makes it look nicer now:

![image](https://user-images.githubusercontent.com/1001176/90198678-4ada8f00-de0d-11ea-8702-7330a9e709dd.png)

Thanks for helping and explanation.

**Comment by RokeJulianLockhart** [comment]
@lephuongbg, https://gitlab.gnome.org/GNOME/gimp/-/issues/10062
