### ISSUE TITLE
Update runtime to 40

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gimp.GIMP#84]

**Comment by Jehan** [comment]
Patches welcome. 🙏

**Comment by Jehan** [comment]
I did make a quick test (#85) but Webkit broke on both supported platforms.

Also with this SDK, we apparently lose ARM support, which kind of sucks and doesn't really make me want to investigate too much. Anyway anyone who wants the runtime update to happen, please propose working patches!

**Comment by skierpage** [comment]
FWIW I ran
`flatpak run --runtime-version=3.38 org.gimp.GIMP`
and GIMP seemed to start up OK. So that's an end-user workaround for this issue.

Thanks for caring about older and lesser architectures.

**Comment by edmundlaugasson** [comment]
Got the message, when updating Flatpak:
```
Info: org.gnome.Platform//3.36 is end-of-life, with reason:
   The GNOME 3.36 runtime is no longer supported as of February 13, 2021. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   org.gimp.GIMP
```
So, hereby I kindly ask you: please update!

**Comment by Jehan** [comment]
Patches are welcome to fix the build with the runtime bump. 👍

**Comment by edmundlaugasson** [comment]
I agree, currently already v40 is out:
```
flatpak search org.gnome.Platform
Name                                      Description                                   Application ID       Version   Branch   Remotes
GNOME Application Platform version 40     Shared libraries used by GNOME applications   org.gnome.Platform             40       flathub
GNOME Application Platform version 3.38   Shared libraries used by GNOME applications   org.gnome.Platform             3.38     flathub
```
information about that version:
```
flatpak remote-info flathub org.gnome.Platform//40
        ID: org.gnome.Platform
       Ref: runtime/org.gnome.Platform/x86_64/40
      Arch: x86_64
    Branch: x86_64
Collection: org.flathub.Stable
  Download: 363,3 MB
 Installed: 975,6 MB

    Commit: f11dade504a555269142b63de3602810b560f583e522af9341d1ff3ccb215847
   Subject: Export org.gnome.Platform
      Date: 2021-03-24 05:19:05 +0000
```
Installed that library version and tested:
`flatpak run --runtime-version=40 org.gimp.GIMP`
Got one message:
`Gtk-Message: Failed to load module "atk-bridge"`
Otherwise GIMP started and worked fine. Couldn't tested thoroughly, but seemed fine.

Patches: sorry, not developer.

**Comment by hfiguiere** [comment]
gtk webkit fail to build because `g_object_ref_sink()` is now a macro but they try to forward declare it. (bad idea). and a couple of other things.

Cooking up a patch, but it takes a while to build on my 4 year old laptop, even with ccache.

**Comment by hfiguiere** [comment]
and plugins will need to be updated too...
