### ISSUE TITLE
Unable to export to HEIF

### ISSUE THREAD

**Issue by FakeShemp** [flathub/org.gimp.GIMP#87]
When exporting to HEIF all I get is

`Unable to find suitable HEIF encoder`

**Comment by Jehan** [comment]
Indeed, missing dependency. This is now fixed and the build is starting any minute now. The build should be automatically published in a few hours. Try to update the flatpak in half a day, and try again.

I am closing the report. If anything is not right even with the new build, please feel free to reopen.

Thanks for the report!
